// <auto-generated />
using System;
using GuestSystemBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuestSystemBack.Migrations
{
    [DbContext(typeof(GuestSystemContext))]
    [Migration("20230213141939_initial_v0.1")]
    partial class initialv01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuestSystemBack.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GuestSystemBack.Models.ExtraDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExtraDocuments");
                });

            modelBuilder.Entity("GuestSystemBack.Models.FormDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExtraDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("FormSubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtraDocumentId");

                    b.HasIndex("FormSubmissionId");

                    b.ToTable("FormDocuments");
                });

            modelBuilder.Entity("GuestSystemBack.Models.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmitterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisiteeId")
                        .HasColumnType("int");

                    b.Property<bool>("WasSubmitByAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SubmitterId");

                    b.HasIndex("VisiteeId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("GuestSystemBack.Models.VisitableEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitableEmployees");
                });

            modelBuilder.Entity("GuestSystemBack.Models.FormDocument", b =>
                {
                    b.HasOne("GuestSystemBack.Models.ExtraDocument", "Document")
                        .WithMany("FormDocuments")
                        .HasForeignKey("ExtraDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSystemBack.Models.FormSubmission", "Form")
                        .WithMany("FormDocuments")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("GuestSystemBack.Models.FormSubmission", b =>
                {
                    b.HasOne("GuestSystemBack.Models.Admin", "Submitter")
                        .WithMany("FormSubmissions")
                        .HasForeignKey("SubmitterId");

                    b.HasOne("GuestSystemBack.Models.VisitableEmployee", "Visitee")
                        .WithMany("FormSubmissions")
                        .HasForeignKey("VisiteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submitter");

                    b.Navigation("Visitee");
                });

            modelBuilder.Entity("GuestSystemBack.Models.Admin", b =>
                {
                    b.Navigation("FormSubmissions");
                });

            modelBuilder.Entity("GuestSystemBack.Models.ExtraDocument", b =>
                {
                    b.Navigation("FormDocuments");
                });

            modelBuilder.Entity("GuestSystemBack.Models.FormSubmission", b =>
                {
                    b.Navigation("FormDocuments");
                });

            modelBuilder.Entity("GuestSystemBack.Models.VisitableEmployee", b =>
                {
                    b.Navigation("FormSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
